const splashes = [
  "Nightmoon Client",
  "Tristen was Here",
  "Wanted by floppy!",
  "Better than Horion!",
  "You haven't seen horion's bank account 🤑 -Floppy, 2024",
  "I just lost my dog!",
  "My brother told me how to chase the bag",
  "You can't crack Nightmoon!",
  "It was bunnytofonfootington, I swear!",
  "Can I get it for free?",
  "iOS version when",
  "Android version when",
  "Xbox version when",
  "PS5 version when",
  "Switch version when",
  "ARASR steals your information!",
  "ARASR wants your mothers credit card",
  "Make ARAS Great Again",
  "Brylan for ARASR president",
  "Tristen was Here",
  "Horion's Killaura xD",
  "This isn't a charity",
  "IOS? LOL",
  "0% Minecraft Vanilla",
  "Overmind_ was here!",
  "Be a real Goatster!",
  "Tristen was Here",
  "Grass is yummy!",
  "Fish 🐟",
  "Here in 2024!",
  "Marketplace is a scam!",
  "Waffle Fries",
  "Tristen was Here",
  "Nightmoon > Horion",
  "Do not join vc1, they're playing the dream song",
  "Tristen was Here",
  "W Tristen",
  "L vyse",
  "L pina",
  "L obaq",
  "L TSL Tobi",
  "Dig straight down!",
  "Ares Utility 🤝 Nightmoon",
  "Please respect the sigma -Purpleish, 2024",
  "Put that cookie down!! -Purpleish, 2024",
  "No -Nornide",
  "Tristen was Here",
  "It's just a Horion skid -Borion Dev Team",
  "ducks are cool"
]
